print("I met a traveller from an antique land,")
print("Who said—“Two vast and trunkless legs of stone")
print("Stand in the desert. . . . Near them, on the sand,")
print("Half sunk a shattered visage lies, whose frown,")
print("And wrinkled lip, and sneer of cold command,")
print("Tell that its sculptor well those passions read")
print("Which yet survive, stamped on these lifeless things,")
print("The hand that mocked them, and the heart that fed;")
print("And on the pedestal, these words appear:")
print("My name is Ozymandias, King of Kings;")
print("Look on my Works, ye Mighty, and despair!")
print("Nothing beside remains. Round the decay")
print("Of that colossal Wreck, boundless and bare")
print("The lone and level sands stretch far away.”")